// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGtFIlmkIsVWj3_C0i3pbdWPc_Ovivcvc',
    appId: '1:64775437473:web:7d8e7a442be4073fce44e0',
    messagingSenderId: '64775437473',
    projectId: 'gisko-007',
    authDomain: 'gisko-007.firebaseapp.com',
    storageBucket: 'gisko-007.appspot.com',
    measurementId: 'G-PHE14DH3QL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzoJm7yh2frhEEUu-cEWfJs-UbkHwuhwM',
    appId: '1:64775437473:android:7495355cc92797d0ce44e0',
    messagingSenderId: '64775437473',
    projectId: 'gisko-007',
    storageBucket: 'gisko-007.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHXJTyeb6UwV9QpxgsivR2xJFxLEM-rBk',
    appId: '1:64775437473:ios:4b62e9b852d8f26bce44e0',
    messagingSenderId: '64775437473',
    projectId: 'gisko-007',
    storageBucket: 'gisko-007.appspot.com',
    androidClientId: '64775437473-ch858brbp7f8vccb3lmh2mkd27as2qqr.apps.googleusercontent.com',
    iosClientId: '64775437473-ioasur503jia8qf76s8st6c0gs5rcqdh.apps.googleusercontent.com',
    iosBundleId: 'com.example.mygisko',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHXJTyeb6UwV9QpxgsivR2xJFxLEM-rBk',
    appId: '1:64775437473:ios:792f5b2c8fa780e2ce44e0',
    messagingSenderId: '64775437473',
    projectId: 'gisko-007',
    storageBucket: 'gisko-007.appspot.com',
    androidClientId: '64775437473-ch858brbp7f8vccb3lmh2mkd27as2qqr.apps.googleusercontent.com',
    iosClientId: '64775437473-0167mqfg31oje97ots2jk9ts9237sdad.apps.googleusercontent.com',
    iosBundleId: 'com.example.mygisko.RunnerTests',
  );
}
